language: c

dist: xenial

os:
 - linux
 - osx

sudo: true

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f /usr/local/include/c++ ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc || true ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf || true ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlkit ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/cask ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install phantomjs ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc gcc-multilib mlton autoconf make ; fi

install:
 - ./autobuild
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --with-compiler=mlkit; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure ; fi
 - travis_wait 50 make mlkit
 - make mlkit_basislibs
 - sudo make install
 - travis_wait 50 make smltojs
 - make smltojs_basislibs
 - sudo make install_smltojs
 - make mlkit_bin_dist

script:
 - make -C test_dev test
 - make -C test test_mlkit
 - make -C test test_mlkit_no_gc
 - make -C js/test test
 - make -C test/explicit_regions all
